apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: agrosolutions-auth
type: Opaque
stringData:
  JWT_ISSUER: "#{JwtIssuer}#"
  JWT_AUDIENCE: "#{JwtAudience}#"
  JWT_KEY: "#{JwtKey}#"
  AUTH_CONNECTION_STRING: "#{AuthConnectionString}#"