services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: auth-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123!"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_password123!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  identity-api:
    build:
      context: .
      dockerfile: AgroSolutions.Identity.API/Dockerfile
    container_name: identity-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      # seu código lê AUTH_CONSTR
      AUTH_CONSTR: "Server=sqlserver;Database=AuthDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;Encrypt=False;"
      ASPNETCORE_ENVIRONMENT: "Development"
      Jwt__Secret: "AgroSolutions_SuperSecretKey_2026_ChangeInProd"
      Jwt__Issuer: "AgroSolutions.Identity"
      Jwt__Audience: "AgroSolutions.Client"
      Jwt__ExpirationMinutes: "60"

    ports:
      - "8080:8080"